import { Link } from 'react-router-dom';
import { Icon, type IconName } from '../../components/Icon';
import { RoutingPreview } from '../../components/RoutingPreview';
const stages: {icon:IconName;title:string;description:string;detail:string}[] = [
  {icon:'globe',title:'A request enters the gateway.',description:'The application passes an allowlisted operation through its customer-side integration before accessing business data.',detail:'Identity and customer selection stay server-side.'},
  {icon:'search',title:'Detection finds the signal.',description:'Deterministic rules recognize reconnaissance, sensitive enumeration, and repeated activity. Raw banking records are not needed to assess the operation.',detail:'Rule matches are recorded as evidence.'},
  {icon:'activity',title:'Risk remembers the session.',description:'The banking adapter combines rule scores with durable session history. Risk does not fall just because a suspicious session makes an ordinary-looking request.',detail:'A score is a heuristic, not a probability.'},
  {icon:'layers',title:'Routing chooses the destination.',description:'Normal operations reach the real synthetic dataset. Suspicious sessions are pinned to isolated deception. Missing authorization or an unavailable decision fails closed.',detail:'AI cannot override a routing decision.'},
  {icon:'terminal',title:'Interactions become evidence.',description:'The gateway reports outcomes and synthetic exposure counts. Persisted events and incident timelines connect each observed operation to its risk and destination.',detail:'Tenant-scoped telemetry. No bank-row upload.'},
  {icon:'shield',title:'The defender investigates.',description:'Inspect the timeline, then request advisory analysis. The current mock provider separates observed activity from inferred objectives and recommends review—not automatic action.',detail:'Facts first. Interpretation second.'},
];
export function HowItWorks(){return <div className="marketing-page"><section className="explain-hero"><span className="section-tag"><Icon name="activity"/> THE PHANTOMLAYER PROTECTION PATH</span><h1>One application.<br/><span>Two data environments.</span></h1><p>Follow a request from the gateway to the investigation. The decision is deterministic; the evidence is yours to inspect.</p></section><div className="explain-layout"><section className="explain-steps" aria-label="Request lifecycle">{stages.map((step,index)=><article key={step.title}><div className="explain-step-number">0{index+1}</div><div><span className="explain-step-icon"><Icon name={step.icon}/></span><h2>{step.title}</h2><p>{step.description}</p><small>{step.detail}</small></div></article>)}</section><aside className="explain-aside"><RoutingPreview/><div className="ui-note"><Icon name="lock"/><p>The bank controls both local data connections. Only metadata and synthetic counts cross the integration boundary.</p></div><div className="explain-scope"><span className="eyebrow">A BOUNDED DEMONSTRATION</span><h3>Real integration. Fictional banking.</h3><p>PhantomBank demonstrates normal traffic, controlled reconnaissance, persistent pinning, and an audit-backed isolation check. It is not a transparent SQL proxy or a production security guarantee.</p></div></aside></div><section className="marketing-cta"><span className="eyebrow">CONNECT THE DOTS</span><h2>Build a clearer<br/><span>picture of the threat.</span></h2><div className="marketing-actions"><Link className="ui-primary" to="/signup">Create your workspace <Icon name="arrow"/></Link><Link className="ui-secondary" to="/protection">Explore protection layers</Link></div></section></div>;}
