import { Link } from 'react-router-dom';
import { Icon, type IconName } from '../../components/Icon';
import { RoutingPreview } from '../../components/RoutingPreview';
const pillars: {icon:IconName; title:string; text:string}[] = [
  {icon:'activity',title:'Detect the signal.',text:'Deterministic rules and session history surface suspicious operations before the gateway chooses a destination.'},
  {icon:'layers',title:'Change the destination.',text:'Divert suspicious sessions into isolated, synthetic data. Ordinary-looking follow-ups stay inside deception.'},
  {icon:'search',title:'Understand the intent.',text:'Investigate a timeline of operations, risk, and exposure. Advisory analysis helps explain the evidence, not control routing.'},
];
export function Landing() {
  return <div className="marketing-page"><section className="marketing-hero"><div><span className="section-tag"><Icon name="shield" /> CYBER DECEPTION INFRASTRUCTURE</span><h1>Let attackers in.<br/><span>Just not where<br className="desktop-break"/> it matters.</span></h1><p>A security layer that gives suspicious traffic a different destination — and your team a clearer picture of the threat.</p><div className="marketing-actions"><Link className="ui-primary" to="/signup">Build your security layer <Icon name="arrow"/></Link><Link className="ui-secondary" to="/how-it-works">Explore the protection path</Link></div><div className="marketing-trust"><span><Icon name="check"/> Customer-side gateway</span><span><Icon name="check"/> Synthetic deception data</span></div></div><RoutingPreview/></section>
    <section className="marketing-principles"><div className="marketing-section-heading"><p className="eyebrow">NOT JUST ANOTHER ALERT</p><h2>Turn suspicious activity<br/><span>into an investigation.</span></h2><p>Keep enforcement deterministic. Keep your data in your environment. Give defenders evidence they can follow.</p></div><div className="marketing-pillar-grid">{pillars.map((pillar,index)=><article key={pillar.title}><div><Icon name={pillar.icon}/><span>0{index+1}</span></div><h3>{pillar.title}</h3><p>{pillar.text}</p></article>)}</div></section>
    <section className="marketing-boundary"><div><span className="section-tag"><Icon name="lock"/> YOUR INFRASTRUCTURE STAYS YOURS</span><h2>A connected control plane.<br/><span>Not a copy of your database.</span></h2><p>The gateway runs inside your environment. PhantomLayer receives operation metadata and synthetic exposure counts — not your database credentials or customer records.</p><Link className="text-link" to="/protection">Explore protection layers <Icon name="arrow"/></Link></div><dl><div><dt><Icon name="server"/> Customer environment</dt><dd>Gateway execution · real data · isolated deception</dd></div><div><dt><Icon name="activity"/> Outbound telemetry</dt><dd>Operations · rule matches · risk · synthetic counts</dd></div><div><dt><Icon name="shield"/> PhantomLayer workspace</dt><dd>Tenant-scoped incidents · timelines · advisory analysis</dd></div></dl></section>
    <section className="marketing-cta"><span className="eyebrow">MAKE THE NEXT MOVE YOURS</span><h2>Give the threat<br/><span>somewhere else to go.</span></h2><p>Start with your organization. Connect your environment on your terms.</p><Link className="ui-primary" to="/signup">Create your workspace <Icon name="arrow"/></Link><small>Explore the local synthetic demonstration. No production-readiness claim.</small></section>
  </div>;
}
