import { Link } from 'react-router-dom';
import { Icon, type IconName } from '../../components/Icon';
const layers: {icon:IconName;name:string;tag:string;description:string;scope:string}[]=[
  {icon:'globe',name:'API protection',tag:'DEMONSTRATED IN PHANTOMBANK',description:'Assess application operations before business SQL. Divert reconnaissance and sensitive enumeration into isolated synthetic data.',scope:'Customer-side bank gateway · session pinning · event telemetry'},
  {icon:'server',name:'Database deception',tag:'CONFIGURATION TYPE',description:'Represent an isolated deception data environment in the control plane. Enforcement requires a compatible local integration; selecting a layer alone does not intercept arbitrary SQL.',scope:'Local data separation · no production database upload'},
  {icon:'layers',name:'Internal protection',tag:'CONFIGURATION TYPE',description:'Model an internal deployment and agent connection. General internal-network detection and lateral-movement coverage are not implemented by the banking demonstration.',scope:'Deployment configuration · outbound agent health'},
  {icon:'shield',name:'Full protection',tag:'COMBINED CONFIGURATION',description:'A combined configuration option accepted by the bank integration. Actual protection extends only as far as the installed customer-side adapters.',scope:'API adapter supported · additional integrations required'},
];
export function Protection(){return <div className="marketing-page"><section className="explain-hero"><span className="section-tag"><Icon name="shield"/> PROTECTION, WITH A CLEAR BOUNDARY</span><h1>Your infrastructure.<br/><span>Your security layer.</span></h1><p>Configure the layer that fits your environment. Connect the integration that enforces it. Keep your data under your control.</p><div className="marketing-actions"><Link className="ui-primary" to="/signup">Configure your workspace <Icon name="arrow"/></Link><Link className="ui-secondary" to="/how-it-works">See how it works</Link></div></section><section className="layer-catalog" aria-label="Protection configuration types">{layers.map((layer,index)=><article key={layer.name}><div className="layer-top"><Icon name={layer.icon}/><span>0{index+1}</span></div><span className="eyebrow">{layer.tag}</span><h2>{layer.name}</h2><p>{layer.description}</p><div className="layer-scope"><Icon name="check"/><span>{layer.scope}</span></div></article>)}</section><section className="marketing-boundary"><div><span className="section-tag"><Icon name="lock"/> ENFORCEMENT IS NOT A CHECKBOX</span><h2>Verify. Connect.<br/><span>Then confirm readiness.</span></h2><p>Domain ownership, an enabled configuration, and an authenticated local agent establish the integration boundary. A healthy heartbeat is a reported connectivity signal, not proof of complete security coverage.</p></div><dl><div><dt><Icon name="globe"/> Verified ownership</dt><dd>DNS verification for your organization's domain.</dd></div><div><dt><Icon name="server"/> Local gateway</dt><dd>Decision before business data access; no allow-on-error bypass.</dd></div><div><dt><Icon name="activity"/> Inspectable evidence</dt><dd>Recorded decisions, synthetic counts and incident timelines.</dd></div></dl></section><section className="marketing-cta"><span className="eyebrow">YOUR NEXT STEP</span><h2>Build your<br/><span>security layer.</span></h2><p>Start with a tenant-scoped workspace. No production credentials required.</p><Link className="ui-primary" to="/signup">Get started <Icon name="arrow"/></Link></section></div>;}
