from datetime import datetime, timezone
from decimal import Decimal

from sqlalchemy.ext.asyncio import AsyncSession

from app.models.schema import (
    Customer,
    Order,
    OrderItem,
    OrderStatus,
    Payment,
    PaymentMethod,
    PaymentStatus,
    Product,
    User,
    UserRole,
)


async def seed_honeypot_database(session: AsyncSession) -> None:
    users = [
        User(
            username="sysadmin",
            email="sysadmin@deception.local",
            password_hash="$2b$12$honeypot_hash_sysadmin",
            full_name="System Administrator",
            role=UserRole.ADMIN,
            is_active=True,
        ),
        User(
            username="mike.ops",
            email="mike.ops@deception.local",
            password_hash="$2b$12$honeypot_hash_mike",
            full_name="Mike Operations",
            role=UserRole.MANAGER,
            is_active=True,
        ),
        User(
            username="sarah.analyst",
            email="sarah.analyst@deception.local",
            password_hash="$2b$12$honeypot_hash_sarah",
            full_name="Sarah Analyst",
            role=UserRole.EMPLOYEE,
            is_active=True,
        ),
        User(
            username="tom.engineer",
            email="tom.engineer@deception.local",
            password_hash="$2b$12$honeypot_hash_tom",
            full_name="Tom Engineer",
            role=UserRole.EMPLOYEE,
            is_active=True,
        ),
        User(
            username="lisa.support",
            email="lisa.support@deception.local",
            password_hash="$2b$12$honeypot_hash_lisa",
            full_name="Lisa Support",
            role=UserRole.EMPLOYEE,
            is_active=True,
        ),
    ]
    session.add_all(users)
    await session.flush()

    customers = [
        Customer(
            email="james.anderson@corp.example",
            first_name="James",
            last_name="Anderson",
            phone="555-0201",
            address_line1="100 Corporate Blvd",
            address_line2="Floor 10",
            city="Metro City",
            state="NY",
            postal_code="10001",
            country="USA",
            assigned_user_id=users[1].id,
            is_active=True,
        ),
        Customer(
            email="linda.thomas@corp.example",
            first_name="Linda",
            last_name="Thomas",
            phone="555-0202",
            address_line1="200 Business Park",
            address_line2="Suite 500",
            city="Tech Valley",
            state="CA",
            postal_code="94001",
            country="USA",
            assigned_user_id=users[1].id,
            is_active=True,
        ),
        Customer(
            email="robert.jackson@corp.example",
            first_name="Robert",
            last_name="Jackson",
            phone="555-0203",
            address_line1="300 Innovation Dr",
            address_line2=None,
            city="Silicon Hills",
            state="TX",
            postal_code="78701",
            country="USA",
            assigned_user_id=users[2].id,
            is_active=True,
        ),
        Customer(
            email="patricia.white@corp.example",
            first_name="Patricia",
            last_name="White",
            phone="555-0204",
            address_line1="400 Enterprise Way",
            address_line2="Building C",
            city="Data Center",
            state="VA",
            postal_code="20101",
            country="USA",
            assigned_user_id=users[2].id,
            is_active=True,
        ),
        Customer(
            email="michael.harris@corp.example",
            first_name="Michael",
            last_name="Harris",
            phone="555-0205",
            address_line1="500 Cloud St",
            address_line2=None,
            city="Server Town",
            state="WA",
            postal_code="98001",
            country="USA",
            assigned_user_id=users[3].id,
            is_active=True,
        ),
        Customer(
            email="jennifer.martin@corp.example",
            first_name="Jennifer",
            last_name="Martin",
            phone="555-0206",
            address_line1="600 Network Ave",
            address_line2="Unit 100",
            city="Fiber City",
            state="CO",
            postal_code="80001",
            country="USA",
            assigned_user_id=users[3].id,
            is_active=True,
        ),
        Customer(
            email="william.thompson@corp.example",
            first_name="William",
            last_name="Thompson",
            phone="555-0207",
            address_line1="700 Protocol Rd",
            address_line2="Floor 3",
            city="Packetville",
            state="MA",
            postal_code="02101",
            country="USA",
            assigned_user_id=users[4].id,
            is_active=True,
        ),
    ]
    session.add_all(customers)
    await session.flush()

    products = [
        Product(
            sku="HP-SERVER-001",
            name="Honeypot Enterprise Server Rack",
            description="High-density compute for simulated workloads",
            price=Decimal("8999.99"),
            cost=Decimal("5500.00"),
            stock_quantity=5,
            is_active=True,
        ),
        Product(
            sku="HP-STORAGE-001",
            name="Honeypot 100TB Storage Array",
            description="Massive capacity for decoy data lakes",
            price=Decimal("12499.99"),
            cost=Decimal("7800.00"),
            stock_quantity=3,
            is_active=True,
        ),
        Product(
            sku="HP-NETWORK-001",
            name="Honeypot 100GbE Switch",
            description="Ultra-low latency for traffic mirroring",
            price=Decimal("4999.99"),
            cost=Decimal("3100.00"),
            stock_quantity=8,
            is_active=True,
        ),
        Product(
            sku="HP-SECURITY-001",
            name="Honeypot Deception Appliance",
            description="Automated threat deception platform",
            price=Decimal("15999.99"),
            cost=Decimal("9500.00"),
            stock_quantity=2,
            is_active=True,
        ),
        Product(
            sku="HP-MONITOR-001",
            name="Honeypot SOC Dashboard Display",
            description="Real-time attacker activity visualization",
            price=Decimal("2499.99"),
            cost=Decimal("1400.00"),
            stock_quantity=12,
            is_active=True,
        ),
        Product(
            sku="HP-SOFTWARE-001",
            name="Honeypot Threat Intelligence Feed",
            description="Curated attacker TTPs and IOCs",
            price=Decimal("499.99"),
            cost=Decimal("50.00"),
            stock_quantity=50,
            is_active=True,
        ),
        Product(
            sku="HP-TRAINING-001",
            name="Honeypot Red Team Exercise Kit",
            description="Controlled adversary simulation tools",
            price=Decimal("2999.99"),
            cost=Decimal("800.00"),
            stock_quantity=10,
            is_active=True,
        ),
        Product(
            sku="HP-CONSULT-001",
            name="Honeypot Security Assessment",
            description="Professional deception strategy consulting",
            price=Decimal("25000.00"),
            cost=Decimal("12000.00"),
            stock_quantity=20,
            is_active=True,
        ),
    ]
    session.add_all(products)
    await session.flush()

    orders = [
        Order(
            order_number="HPD-2024-0001",
            customer_id=customers[0].id,
            status=OrderStatus.DELIVERED,
            subtotal=Decimal("15999.99"),
            tax_amount=Decimal("1279.99"),
            shipping_amount=Decimal("250.00"),
            total_amount=Decimal("17529.98"),
            notes="Priority deployment - SOC integration",
        ),
        Order(
            order_number="HPD-2024-0002",
            customer_id=customers[1].id,
            status=OrderStatus.SHIPPED,
            subtotal=Decimal("17499.98"),
            tax_amount=Decimal("1399.99"),
            shipping_amount=Decimal("300.00"),
            total_amount=Decimal("19199.97"),
            notes="Rack mounting hardware included",
        ),
        Order(
            order_number="HPD-2024-0003",
            customer_id=customers[2].id,
            status=OrderStatus.CONFIRMED,
            subtotal=Decimal("7499.98"),
            tax_amount=Decimal("599.99"),
            shipping_amount=Decimal("150.00"),
            total_amount=Decimal("8249.97"),
            notes="Phase 1 of 3 deployment",
        ),
        Order(
            order_number="HPD-2024-0004",
            customer_id=customers[3].id,
            status=OrderStatus.DELIVERED,
            subtotal=Decimal("2999.99"),
            tax_amount=Decimal("239.99"),
            shipping_amount=Decimal("75.00"),
            total_amount=Decimal("3314.98"),
            notes="Annual subscription",
        ),
        Order(
            order_number="HPD-2024-0005",
            customer_id=customers[4].id,
            status=OrderStatus.PENDING,
            subtotal=Decimal("27999.98"),
            tax_amount=Decimal("2239.99"),
            shipping_amount=Decimal("500.00"),
            total_amount=Decimal("30739.97"),
            notes="Custom configuration required",
        ),
        Order(
            order_number="HPD-2024-0006",
            customer_id=customers[5].id,
            status=OrderStatus.CONFIRMED,
            subtotal=Decimal("5499.98"),
            tax_amount=Decimal("439.99"),
            shipping_amount=Decimal("100.00"),
            total_amount=Decimal("6039.97"),
            notes="Training materials included",
        ),
        Order(
            order_number="HPD-2024-0007",
            customer_id=customers[6].id,
            status=OrderStatus.SHIPPED,
            subtotal=Decimal("15499.98"),
            tax_amount=Decimal("1239.99"),
            shipping_amount=Decimal("200.00"),
            total_amount=Decimal("16939.97"),
            notes="Expedited - incident response prep",
        ),
        Order(
            order_number="HPD-2024-0008",
            customer_id=customers[0].id,
            status=OrderStatus.CONFIRMED,
            subtotal=Decimal("4999.99"),
            tax_amount=Decimal("399.99"),
            shipping_amount=Decimal("75.00"),
            total_amount=Decimal("5474.98"),
            notes="Add-on to HPD-2024-0001",
        ),
    ]
    session.add_all(orders)
    await session.flush()

    order_items = [
        OrderItem(
            order_id=orders[0].id,
            product_id=products[3].id,
            quantity=1,
            unit_price=products[3].price,
            total_price=products[3].price,
        ),
        OrderItem(
            order_id=orders[1].id,
            product_id=products[0].id,
            quantity=1,
            unit_price=products[0].price,
            total_price=products[0].price,
        ),
        OrderItem(
            order_id=orders[1].id,
            product_id=products[1].id,
            quantity=1,
            unit_price=products[1].price,
            total_price=products[1].price,
        ),
        OrderItem(
            order_id=orders[2].id,
            product_id=products[2].id,
            quantity=1,
            unit_price=products[2].price,
            total_price=products[2].price,
        ),
        OrderItem(
            order_id=orders[2].id,
            product_id=products[4].id,
            quantity=1,
            unit_price=products[4].price,
            total_price=products[4].price,
        ),
        OrderItem(
            order_id=orders[3].id,
            product_id=products[5].id,
            quantity=1,
            unit_price=products[5].price,
            total_price=products[5].price,
        ),
        OrderItem(
            order_id=orders[4].id,
            product_id=products[0].id,
            quantity=1,
            unit_price=products[0].price,
            total_price=products[0].price,
        ),
        OrderItem(
            order_id=orders[4].id,
            product_id=products[7].id,
            quantity=1,
            unit_price=products[7].price,
            total_price=products[7].price,
        ),
        OrderItem(
            order_id=orders[5].id,
            product_id=products[6].id,
            quantity=1,
            unit_price=products[6].price,
            total_price=products[6].price,
        ),
        OrderItem(
            order_id=orders[5].id,
            product_id=products[5].id,
            quantity=1,
            unit_price=products[5].price,
            total_price=products[5].price,
        ),
        OrderItem(
            order_id=orders[6].id,
            product_id=products[3].id,
            quantity=1,
            unit_price=products[3].price,
            total_price=products[3].price,
        ),
        OrderItem(
            order_id=orders[7].id,
            product_id=products[2].id,
            quantity=1,
            unit_price=products[2].price,
            total_price=products[2].price,
        ),
    ]
    session.add_all(order_items)
    await session.flush()

    payments = [
        Payment(
            order_id=orders[0].id,
            payment_method=PaymentMethod.BANK_TRANSFER,
            status=PaymentStatus.COMPLETED,
            amount=orders[0].total_amount,
            transaction_id="hp_txn_001",
            processed_at=datetime(2024, 1, 10, 9, 0, tzinfo=timezone.utc),
        ),
        Payment(
            order_id=orders[1].id,
            payment_method=PaymentMethod.CREDIT_CARD,
            status=PaymentStatus.COMPLETED,
            amount=orders[1].total_amount,
            transaction_id="hp_txn_002",
            processed_at=datetime(2024, 1, 22, 13, 30, tzinfo=timezone.utc),
        ),
        Payment(
            order_id=orders[2].id,
            payment_method=PaymentMethod.BANK_TRANSFER,
            status=PaymentStatus.COMPLETED,
            amount=orders[2].total_amount,
            transaction_id="hp_txn_003",
            processed_at=datetime(2024, 2, 5, 10, 15, tzinfo=timezone.utc),
        ),
        Payment(
            order_id=orders[3].id,
            payment_method=PaymentMethod.PAYPAL,
            status=PaymentStatus.COMPLETED,
            amount=orders[3].total_amount,
            transaction_id="hp_txn_004",
            processed_at=datetime(2024, 2, 12, 15, 45, tzinfo=timezone.utc),
        ),
        Payment(
            order_id=orders[4].id,
            payment_method=PaymentMethod.BANK_TRANSFER,
            status=PaymentStatus.PENDING,
            amount=orders[4].total_amount,
            transaction_id=None,
            processed_at=None,
        ),
        Payment(
            order_id=orders[5].id,
            payment_method=PaymentMethod.CREDIT_CARD,
            status=PaymentStatus.COMPLETED,
            amount=orders[5].total_amount,
            transaction_id="hp_txn_006",
            processed_at=datetime(2024, 3, 1, 11, 20, tzinfo=timezone.utc),
        ),
        Payment(
            order_id=orders[6].id,
            payment_method=PaymentMethod.BANK_TRANSFER,
            status=PaymentStatus.COMPLETED,
            amount=orders[6].total_amount,
            transaction_id="hp_txn_007",
            processed_at=datetime(2024, 3, 10, 8, 30, tzinfo=timezone.utc),
        ),
        Payment(
            order_id=orders[7].id,
            payment_method=PaymentMethod.CREDIT_CARD,
            status=PaymentStatus.COMPLETED,
            amount=orders[7].total_amount,
            transaction_id="hp_txn_008",
            processed_at=datetime(2024, 3, 15, 14, 0, tzinfo=timezone.utc),
        ),
    ]
    session.add_all(payments)
    await session.commit()