from datetime import datetime, timezone
from decimal import Decimal

from sqlalchemy.ext.asyncio import AsyncSession

from app.models.schema import (
    Customer,
    Order,
    OrderItem,
    OrderStatus,
    Payment,
    PaymentMethod,
    PaymentStatus,
    Product,
    User,
    UserRole,
)


async def seed_real_database(session: AsyncSession) -> None:
    users = [
        User(
            username="admin",
            email="admin@phantomlayer.demo",
            password_hash="$2b$12$demo_hash_admin",
            full_name="System Administrator",
            role=UserRole.ADMIN,
            is_active=True,
        ),
        User(
            username="john.manager",
            email="john.manager@phantomlayer.demo",
            password_hash="$2b$12$demo_hash_john",
            full_name="John Smith",
            role=UserRole.MANAGER,
            is_active=True,
        ),
        User(
            username="jane.employee",
            email="jane.employee@phantomlayer.demo",
            password_hash="$2b$12$demo_hash_jane",
            full_name="Jane Doe",
            role=UserRole.EMPLOYEE,
            is_active=True,
        ),
        User(
            username="bob.employee",
            email="bob.employee@phantomlayer.demo",
            password_hash="$2b$12$demo_hash_bob",
            full_name="Bob Wilson",
            role=UserRole.EMPLOYEE,
            is_active=True,
        ),
    ]
    session.add_all(users)
    await session.flush()

    customers = [
        Customer(
            email="alice.johnson@email.com",
            first_name="Alice",
            last_name="Johnson",
            phone="555-0101",
            address_line1="123 Main St",
            address_line2="Apt 4B",
            city="Springfield",
            state="IL",
            postal_code="62701",
            country="USA",
            assigned_user_id=users[1].id,
            is_active=True,
        ),
        Customer(
            email="bob.williams@email.com",
            first_name="Bob",
            last_name="Williams",
            phone="555-0102",
            address_line1="456 Oak Ave",
            address_line2=None,
            city="Riverside",
            state="CA",
            postal_code="92501",
            country="USA",
            assigned_user_id=users[1].id,
            is_active=True,
        ),
        Customer(
            email="carol.davis@email.com",
            first_name="Carol",
            last_name="Davis",
            phone="555-0103",
            address_line1="789 Pine Rd",
            address_line2="Suite 200",
            city="Lakeside",
            state="TX",
            postal_code="75001",
            country="USA",
            assigned_user_id=users[2].id,
            is_active=True,
        ),
        Customer(
            email="david.miller@email.com",
            first_name="David",
            last_name="Miller",
            phone="555-0104",
            address_line1="321 Elm St",
            address_line2=None,
            city="Hillview",
            state="FL",
            postal_code="33001",
            country="USA",
            assigned_user_id=users[2].id,
            is_active=True,
        ),
        Customer(
            email="eva.garcia@email.com",
            first_name="Eva",
            last_name="Garcia",
            phone="555-0105",
            address_line1="654 Maple Dr",
            address_line2="Unit 3",
            city="Brookfield",
            state="NY",
            postal_code="10001",
            country="USA",
            assigned_user_id=users[3].id,
            is_active=True,
        ),
    ]
    session.add_all(customers)
    await session.flush()

    products = [
        Product(
            sku="PL-LAPTOP-001",
            name="PhantomLayer Laptop Pro 15",
            description="High-performance laptop for security professionals",
            price=Decimal("1299.99"),
            cost=Decimal("850.00"),
            stock_quantity=25,
            is_active=True,
        ),
        Product(
            sku="PL-MONITOR-001",
            name="PhantomLayer 27\" 4K Monitor",
            description="Ultra-sharp display for threat analysis",
            price=Decimal("449.99"),
            cost=Decimal("280.00"),
            stock_quantity=40,
            is_active=True,
        ),
        Product(
            sku="PL-KEYBOARD-001",
            name="PhantomLayer Mechanical Keyboard",
            description="Tactile switches optimized for long coding sessions",
            price=Decimal("179.99"),
            cost=Decimal("95.00"),
            stock_quantity=60,
            is_active=True,
        ),
        Product(
            sku="PL-MOUSE-001",
            name="PhantomLayer Precision Mouse",
            description="High-DPI mouse for precise navigation",
            price=Decimal("79.99"),
            cost=Decimal("35.00"),
            stock_quantity=80,
            is_active=True,
        ),
        Product(
            sku="PL-HEADSET-001",
            name="PhantomLayer Noise-Canceling Headset",
            description="Clear audio for incident response calls",
            price=Decimal("199.99"),
            cost=Decimal("110.00"),
            stock_quantity=35,
            is_active=True,
        ),
        Product(
            sku="PL-DOCK-001",
            name="PhantomLayer Thunderbolt Dock",
            description="Expand connectivity for multi-monitor setups",
            price=Decimal("249.99"),
            cost=Decimal("145.00"),
            stock_quantity=20,
            is_active=True,
        ),
        Product(
            sku="PL-SSD-001",
            name="PhantomLayer 2TB NVMe SSD",
            description="Fast encrypted storage for evidence",
            price=Decimal("229.99"),
            cost=Decimal("130.00"),
            stock_quantity=50,
            is_active=True,
        ),
        Product(
            sku="PL-SECURITY-001",
            name="PhantomLayer Security Key Pack",
            description="Hardware authentication keys (pack of 2)",
            price=Decimal("89.99"),
            cost=Decimal("45.00"),
            stock_quantity=100,
            is_active=True,
        ),
    ]
    session.add_all(products)
    await session.flush()

    orders = [
        Order(
            order_number="ORD-2024-0001",
            customer_id=customers[0].id,
            status=OrderStatus.DELIVERED,
            subtotal=Decimal("1299.99"),
            tax_amount=Decimal("103.99"),
            shipping_amount=Decimal("15.00"),
            total_amount=Decimal("1418.98"),
            notes="Expedited shipping requested",
        ),
        Order(
            order_number="ORD-2024-0002",
            customer_id=customers[1].id,
            status=OrderStatus.SHIPPED,
            subtotal=Decimal("529.98"),
            tax_amount=Decimal("42.40"),
            shipping_amount=Decimal("12.00"),
            total_amount=Decimal("584.38"),
            notes=None,
        ),
        Order(
            order_number="ORD-2024-0003",
            customer_id=customers[2].id,
            status=OrderStatus.CONFIRMED,
            subtotal=Decimal("479.97"),
            tax_amount=Decimal("38.40"),
            shipping_amount=Decimal("10.00"),
            total_amount=Decimal("528.37"),
            notes="Gift wrap requested",
        ),
        Order(
            order_number="ORD-2024-0004",
            customer_id=customers[3].id,
            status=OrderStatus.PENDING,
            subtotal=Decimal("229.99"),
            tax_amount=Decimal("18.40"),
            shipping_amount=Decimal("8.00"),
            total_amount=Decimal("256.39"),
            notes=None,
        ),
        Order(
            order_number="ORD-2024-0005",
            customer_id=customers[4].id,
            status=OrderStatus.DELIVERED,
            subtotal=Decimal("339.98"),
            tax_amount=Decimal("27.20"),
            shipping_amount=Decimal("0.00"),
            total_amount=Decimal("367.18"),
            notes="Free shipping promotion",
        ),
        Order(
            order_number="ORD-2024-0006",
            customer_id=customers[0].id,
            status=OrderStatus.CONFIRMED,
            subtotal=Decimal("899.97"),
            tax_amount=Decimal("72.00"),
            shipping_amount=Decimal("15.00"),
            total_amount=Decimal("986.97"),
            notes=None,
        ),
    ]
    session.add_all(orders)
    await session.flush()

    order_items = [
        OrderItem(
            order_id=orders[0].id,
            product_id=products[0].id,
            quantity=1,
            unit_price=products[0].price,
            total_price=products[0].price,
        ),
        OrderItem(
            order_id=orders[1].id,
            product_id=products[1].id,
            quantity=1,
            unit_price=products[1].price,
            total_price=products[1].price,
        ),
        OrderItem(
            order_id=orders[1].id,
            product_id=products[2].id,
            quantity=1,
            unit_price=products[2].price,
            total_price=products[2].price,
        ),
        OrderItem(
            order_id=orders[2].id,
            product_id=products[2].id,
            quantity=1,
            unit_price=products[2].price,
            total_price=products[2].price,
        ),
        OrderItem(
            order_id=orders[2].id,
            product_id=products[3].id,
            quantity=1,
            unit_price=products[3].price,
            total_price=products[3].price,
        ),
        OrderItem(
            order_id=orders[2].id,
            product_id=products[7].id,
            quantity=1,
            unit_price=products[7].price,
            total_price=products[7].price,
        ),
        OrderItem(
            order_id=orders[3].id,
            product_id=products[6].id,
            quantity=1,
            unit_price=products[6].price,
            total_price=products[6].price,
        ),
        OrderItem(
            order_id=orders[4].id,
            product_id=products[4].id,
            quantity=1,
            unit_price=products[4].price,
            total_price=products[4].price,
        ),
        OrderItem(
            order_id=orders[4].id,
            product_id=products[7].id,
            quantity=1,
            unit_price=products[7].price,
            total_price=products[7].price,
        ),
        OrderItem(
            order_id=orders[5].id,
            product_id=products[1].id,
            quantity=1,
            unit_price=products[1].price,
            total_price=products[1].price,
        ),
        OrderItem(
            order_id=orders[5].id,
            product_id=products[3].id,
            quantity=2,
            unit_price=products[3].price,
            total_price=products[3].price * 2,
        ),
    ]
    session.add_all(order_items)
    await session.flush()

    payments = [
        Payment(
            order_id=orders[0].id,
            payment_method=PaymentMethod.CREDIT_CARD,
            status=PaymentStatus.COMPLETED,
            amount=orders[0].total_amount,
            transaction_id="txn_demo_001",
            processed_at=datetime(2024, 1, 15, 10, 30, tzinfo=timezone.utc),
        ),
        Payment(
            order_id=orders[1].id,
            payment_method=PaymentMethod.PAYPAL,
            status=PaymentStatus.COMPLETED,
            amount=orders[1].total_amount,
            transaction_id="txn_demo_002",
            processed_at=datetime(2024, 1, 20, 14, 45, tzinfo=timezone.utc),
        ),
        Payment(
            order_id=orders[2].id,
            payment_method=PaymentMethod.CREDIT_CARD,
            status=PaymentStatus.COMPLETED,
            amount=orders[2].total_amount,
            transaction_id="txn_demo_003",
            processed_at=datetime(2024, 2, 1, 9, 15, tzinfo=timezone.utc),
        ),
        Payment(
            order_id=orders[3].id,
            payment_method=PaymentMethod.BANK_TRANSFER,
            status=PaymentStatus.PENDING,
            amount=orders[3].total_amount,
            transaction_id=None,
            processed_at=None,
        ),
        Payment(
            order_id=orders[4].id,
            payment_method=PaymentMethod.DEBIT_CARD,
            status=PaymentStatus.COMPLETED,
            amount=orders[4].total_amount,
            transaction_id="txn_demo_005",
            processed_at=datetime(2024, 2, 10, 16, 20, tzinfo=timezone.utc),
        ),
        Payment(
            order_id=orders[5].id,
            payment_method=PaymentMethod.CREDIT_CARD,
            status=PaymentStatus.COMPLETED,
            amount=orders[5].total_amount,
            transaction_id="txn_demo_006",
            processed_at=datetime(2024, 2, 15, 11, 0, tzinfo=timezone.utc),
        ),
    ]
    session.add_all(payments)
    await session.commit()