"""
Phase 11 – AI Incident Analysis: Data Models

Security boundary notes
-----------------------
- SanitizedSessionPayload and SanitizedTimelineStep are the ONLY objects ever
  sent to the AI provider.  They contain exclusively synthetic honeypot
  telemetry (operation names, risk scores, rule names, entity type/count
  information, timestamps).  They NEVER contain:
    • Production database rows or credentials
    • Real user PII
    • Connection strings or API keys
    • Raw request bodies or HTTP headers beyond what is explicitly whitelisted
- IncidentAnalysisResponse is purely advisory.  It MUST NOT influence routing.
- Fields clearly labelled "AI inference" must be treated as advisory only.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class AnalysisStatus(str, Enum):
    PENDING = "pending"
    COMPLETED = "completed"
    FAILED = "failed"


class ActionPriority(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class PatternConfidence(str, Enum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


# ---------------------------------------------------------------------------
# Sanitized payload – the ONLY data sent to the AI client
# ---------------------------------------------------------------------------


class SanitizedTimelineStep(BaseModel):
    """
    One interaction record stripped of any raw data payloads.
    Only telemetry is retained: operation name, risk score, rule names,
    entity type + count (not actual values), attack stage at that step.
    """

    step: int
    timestamp_utc: str  # ISO-8601, UTC only – no timezone-leaking wall clocks
    operation: str  # e.g. "get_customers", "list_tables"
    risk_score: int = Field(ge=0, le=100)
    attack_stage: str  # value of AttackStage enum
    triggered_rule_names: list[str] = Field(default_factory=list)
    entities_exposed_counts: dict[str, int] = Field(
        default_factory=dict,
        description="e.g. {'customers': 3, 'orders': 2} — counts only, never values",
    )
    success: bool


class SanitizedSessionPayload(BaseModel):
    """
    The complete sanitized representation of an attacker session sent to the AI.

    WHITELIST POLICY: only the fields defined here may be sent to the AI.
    No other data is permitted to cross the boundary.
    """

    session_id: str
    session_duration_seconds: Optional[float] = None
    final_attack_stage: str
    total_interactions: int
    unique_operations: list[str]
    triggered_rule_names: list[str]  # unique, de-duplicated
    max_risk_score: int = Field(ge=0, le=100)
    avg_risk_score: float = Field(ge=0.0, le=100.0)
    exposed_entity_counts: dict[str, int] = Field(
        default_factory=dict,
        description="Total unique synthetic entity counts across the session",
    )
    timeline: list[SanitizedTimelineStep]
    correlated_event_count: int = 0


# ---------------------------------------------------------------------------
# AI analysis output models
# ---------------------------------------------------------------------------


class AttackTimelineStep(BaseModel):
    """Structured AI annotation of one timeline step."""

    step: int
    operation: str
    attack_stage: str
    inferred_intent: str = Field(
        description="[AI INFERENCE] What the attacker likely intended with this step"
    )


class AttackPattern(BaseModel):
    """A suspicious behavioral pattern identified by the AI."""

    pattern_name: str
    description: str
    confidence: PatternConfidence


class RecommendedAction(BaseModel):
    """A defensive action recommended by the AI."""

    action_type: str
    description: str
    priority: ActionPriority


class IncidentAnalysisResponse(BaseModel):
    """
    Structured output from the AI analysis client.

    Fields marked [AI INFERENCE] are generated by the language model and must
    be treated as advisory intelligence, not ground truth.
    """

    session_id: str
    incident_summary: str
    attack_stage_progression: list[str]
    timeline: list[AttackTimelineStep]
    observed_behavior: str
    operations_performed: list[str]
    sensitive_resources_targeted: list[str]
    exposed_synthetic_entities: dict[str, int]
    risk_assessment: str
    suspicious_patterns: list[AttackPattern]
    likely_objective: str = Field(
        description="[AI INFERENCE] The inferred ultimate goal of this attack session"
    )
    defensive_recommendations: list[RecommendedAction]
    limitations: str = Field(
        description="Disclaimer on AI confidence, coverage, and missing context"
    )
    analysis_provider: str = "mock"


# ---------------------------------------------------------------------------
# Incident analysis request / response for the API layer
# ---------------------------------------------------------------------------


class IncidentAnalysisRequest(BaseModel):
    """Request body for POST /api/v1/incidents/{session_id}/analyze."""

    force_reanalysis: bool = Field(
        default=False,
        description="If True, re-run analysis even if a report already exists",
    )


# ---------------------------------------------------------------------------
# Persistent incident report (stored in IncidentReportStore)
# ---------------------------------------------------------------------------


class IncidentReport(BaseModel):
    """Stored artifact: pairs a sanitized payload with its AI analysis."""

    report_id: UUID = Field(default_factory=uuid4)
    session_id: str
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    status: AnalysisStatus = AnalysisStatus.PENDING
    sanitized_payload: Optional[SanitizedSessionPayload] = None
    analysis: Optional[IncidentAnalysisResponse] = None
    error: Optional[str] = None


# ---------------------------------------------------------------------------
# API list / detail response models
# ---------------------------------------------------------------------------


class IncidentReportSummary(BaseModel):
    report_id: str
    session_id: str
    created_at: str
    status: AnalysisStatus
    final_attack_stage: Optional[str] = None
    likely_objective: Optional[str] = None


class IncidentReportListResponse(BaseModel):
    reports: list[IncidentReportSummary]
    total: int


class IncidentReportDetailResponse(BaseModel):
    report_id: str
    session_id: str
    created_at: str
    status: AnalysisStatus
    sanitized_payload: Optional[SanitizedSessionPayload] = None
    analysis: Optional[IncidentAnalysisResponse] = None
    error: Optional[str] = None
