import { useCallback, useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Badge } from '../../components/Badge';
import { Button } from '../../components/Button';
import { EmptyState } from '../../components/EmptyState';
import { Icon } from '../../components/Icon';
import { apiGet } from '../../lib/api';
interface SecurityEvent {event_id?:string; session_id?:string; timestamp?:string; event_type?:string; source?:string; original_target?:string; final_target?:string; operation?:string; risk_score?:number; severity?:string; suspicious?:boolean; triggered_rules?:unknown[]; reasons?:string[]}
const label=(value?:string)=>(value || 'assessment').replaceAll('_',' ');
const formatTime=(value?:string)=>value ? new Date(value).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'}) : '—';
const formatDate=(value?:string)=>value ? new Date(value).toLocaleDateString([], {day:'2-digit',month:'short'}) : '—';
const targetVariant=(target?:string)=>target==='real'?'success' as const:target==='honeypot'?'purple' as const:target==='blocked'?'danger' as const:'neutral' as const;
const riskVariant=(risk=0)=>risk>=76?'danger' as const:risk>=51?'warning' as const:risk>=31?'info' as const:'neutral' as const;
function ruleName(rule:unknown) {if(typeof rule==='string')return rule;if(rule && typeof rule==='object'){const r=rule as Record<string,unknown>;return String(r.rule || r.name || r.rule_id || 'Recorded rule');}return 'Recorded rule';}
export function Events() {
  const [params, setParams] = useSearchParams();
  const sessionFilter = params.get('session') || '';
  const [events,setEvents]=useState<SecurityEvent[]>([]);
  const [loading,setLoading]=useState(true);
  const [refreshing,setRefreshing]=useState(false);
  const [error,setError]=useState('');
  const [targetFilter,setTargetFilter]=useState('all');
  const [severityFilter,setSeverityFilter]=useState('all');
  const [search,setSearch]=useState('');
  const loadEvents=useCallback(async()=>{setRefreshing(true);try{const response=await apiGet<{events?:SecurityEvent[]}>(`/security/events?limit=100${sessionFilter ? `&session_id=${encodeURIComponent(sessionFilter)}` : ''}`);setEvents(response.events || []);setError('');}catch(e){setError(e instanceof Error?e.message:'Unable to load security events.');}finally{setLoading(false);setRefreshing(false);}},[sessionFilter]);
  useEffect(()=>{setEvents([]);setLoading(true);void loadEvents();const timer=window.setInterval(loadEvents,10000);return()=>window.clearInterval(timer);},[loadEvents]);
  const filtered=events.filter(event=>(targetFilter==='all'||event.final_target?.toLowerCase()===targetFilter)&&(severityFilter==='all'||event.severity?.toLowerCase()===severityFilter)&&[event.operation,event.session_id,event.event_type,event.source].some(v=>(v||'').toLowerCase().includes(search.toLowerCase().trim())));
  return <div className="customer-events-page"><section className="customer-page-header"><div><span className="customer-eyebrow">THE SECURITY EVENT CONSOLE</span><h1>Every signal. In context.</h1><p>Request decisions, rule matches, and routing evidence from your organization.</p></div><div className="events-total"><strong>{loading?'—':events.length}</strong><span>IN CURRENT FEED</span></div></section>
    {sessionFilter && <div className="session-filter-banner"><div><span className="eyebrow">SESSION-SCOPED EVIDENCE</span><code>{sessionFilter}</code></div><Button variant="secondary" size="small" onClick={() => {setParams({});setSearch('');setTargetFilter('all');setSeverityFilter('all');}}>Show all sessions</Button></div>}
    <section className="events-toolbar" aria-label="Filter events"><label className="events-search"><Icon name="search"/><input aria-label="Search security events" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search an operation, session, or event…"/><span>{filtered.length} matching events · latest 100 · refreshes every 10s</span></label><div className="events-filter-group"><span>DESTINATION</span><div className="events-filter-buttons">{[['all','All'],['real','Real'],['honeypot','Deception'],['blocked','Blocked']].map(([value,text])=><button key={value} type="button" aria-pressed={targetFilter===value} className={targetFilter===value?'events-filter-active':''} onClick={()=>setTargetFilter(value)}>{text}</button>)}</div></div><div className="events-filter-group"><span>SEVERITY</span><div className="events-filter-buttons">{['all','critical','high','medium','low'].map(value=><button key={value} type="button" aria-pressed={severityFilter===value} className={severityFilter===value?'events-filter-active':''} onClick={()=>setSeverityFilter(value)}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div></div><Button className="events-refresh-button" variant="secondary" size="small" icon={<Icon name="refresh"/>} disabled={refreshing} onClick={()=>void loadEvents()}>{refreshing?'Refreshing…':'Refresh'}</Button></section>
    {error&&<div className="ui-alert ui-alert-error" role="alert"><Icon name="alert"/><div><strong>Event feed unavailable</strong><p>{error} {events.length?'Showing the last successful feed.':'Try refreshing.'}</p></div></div>}
    <section className="events-panel" aria-label="Recorded security events"><div className="event-console-caption"><Icon name="terminal"/><span>SECURITY STREAM</span><span><i className="status-dot violet"/> Select an event to inspect evidence</span></div><div className="events-table-header" aria-hidden="true"><span>OBSERVED</span><span>EVENT</span><span>OPERATION / SESSION</span><span>DESTINATION</span><span>RISK</span><span>SEVERITY</span></div>
      {loading?<div className="skeleton-list" role="status" aria-label="Loading security telemetry"><i/><i/><i/></div>:!filtered.length?<EmptyState icon={<Icon name="activity"/>} title={events.length?'No matching signals':'Waiting for the first signal'} description={events.length?'Try another destination, severity, or search term.':'Recorded security activity will appear here when your integration sends telemetry.'} action={events.length?<Button variant="secondary" size="small" onClick={()=>{setSearch('');setTargetFilter('all');setSeverityFilter('all');}}>Clear filters</Button>:<Link className="text-link" to="/dashboard/protection">Review protection →</Link>}/>:<div className="events-list">{filtered.map((event,index)=><details className="event-entry" key={event.event_id||index}><summary className="security-event-row"><div className="security-event-time"><strong>{formatTime(event.timestamp)}</strong><span>{formatDate(event.timestamp)}</span></div><div className="security-event-main"><div className="security-event-title"><i className={event.suspicious?'event-indicator event-indicator-danger':'event-indicator'}/><strong>{label(event.event_type)}</strong></div><span>{label(event.source)}</span></div><div className="security-event-operation"><code>{event.operation||'unknown'}</code>{event.session_id&&<span title={event.session_id}>{event.session_id.slice(-12)}</span>}</div><div><Badge variant={targetVariant(event.final_target)} size="small">{event.final_target==='honeypot'?'Deception':label(event.final_target)}</Badge></div><div className="security-event-risk"><strong>{event.risk_score??'—'}</strong><div className="event-risk-bar" aria-hidden="true"><i style={{width:`${Math.max(0,Math.min(event.risk_score??0,100))}%`}}/></div></div><div><Badge variant={riskVariant(event.risk_score)} size="small">{event.severity ? label(event.severity) : 'Unrated'}</Badge></div></summary><div className="event-expanded"><dl><div><dt>Event ID</dt><dd><code>{event.event_id||'Not supplied'}</code></dd></div><div><dt>Session</dt><dd><code>{event.session_id||'No attack session attached'}</code></dd></div><div><dt>Routing evidence</dt><dd>{label(event.original_target)} → {event.final_target==='honeypot'?'isolated deception':label(event.final_target)}</dd></div></dl><div><span className="eyebrow">RULE MATCHES</span><div className="event-rules">{event.triggered_rules?.length?event.triggered_rules.map((rule,i)=><code key={i}>{ruleName(rule)}</code>):<span>No rule matches attached to this event.</span>}</div>{event.reasons?.length?<ul>{event.reasons.map((reason,i)=><li key={i}>{reason}</li>)}</ul>:null}</div>{event.session_id&&<Link className="text-link" to="/dashboard/sessions">Explore recorded sessions <Icon name="arrow"/></Link>}</div></details>)}</div>}
    </section><section className="events-explanation"><div><span className="customer-eyebrow">OBSERVATIONS, NOT ASSUMPTIONS</span><h2>Follow the decision, not just the alert.</h2><p>Detection and routing events describe recorded operations. Synthetic exposure and intent analysis are separate evidence layers; this feed is not a claim about every request outside the integration.</p></div><div className="events-legend"><div><span className="legend-dot legend-real"/><strong>REAL</strong><small>Allowed destination</small></div><div><span className="legend-dot legend-honeypot"/><strong>DECEPTION</strong><small>Synthetic environment</small></div></div></section>
  </div>;
}
