import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { apiGet } from '../../lib/api';
import { useOrganization } from '../../hooks/useOrganization';
import { Icon } from '../../components/Icon';
import { Button } from '../../components/Button';
import { StatusPill } from '../../components/StatusPill';
import { EmptyState } from '../../components/EmptyState';

type Incident = {incident_id:string; session_id:string; risk_score:number; severity:string; attack_stage:string; interaction_count:number; created_at:string; status:string};
type Event = {event_id:string; timestamp:string; event_type?:string; operation:string; session_id:string|null; final_target:string|null; risk_score:number|null; suspicious?:boolean};
type Stats = {total_incidents:number; honeypot_interactions:number; requests_routed_to_honeypot:number; requests_routed_to_real:number; blocked_requests:number};
const human = (v:string) => v.replaceAll('_',' ');
const time = (v:string) => new Date(v).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'});

export function Overview() {
  const [snapshot, setSnapshot] = useState<{stats:Stats; incidents:Incident[]; events:Event[]}|null>(null);
  const [error,setError] = useState('');
  const [updated,setUpdated] = useState<Date|null>(null);
  const [loading,setLoading] = useState(true);
  const [refreshing,setRefreshing] = useState(false);
  const organization = useOrganization();
  const refresh = useCallback(async () => {
    setRefreshing(true);
    try {
      const [stats,incidents,events] = await Promise.all([apiGet<Stats>('/security/stats'),apiGet<{incidents:Incident[]}>('/incidents?limit=12'),apiGet<{events:Event[]}>('/security/events?limit=100')]);
      setSnapshot({stats,incidents:incidents.incidents,events:events.events});setUpdated(new Date());setError('');
    } catch(e) {setError(e instanceof Error ? e.message : 'Telemetry unavailable');}
    finally {setLoading(false);setRefreshing(false);}
  },[]);
  useEffect(() => {void refresh();const timer=window.setInterval(refresh,10000);return()=>window.clearInterval(timer);},[refresh]);
  const {activeProtection, domains, agents, isLoading: orgLoading} = organization;
  const stats=snapshot?.stats;
  const lead=snapshot?.incidents[0];
  const total=(stats?.requests_routed_to_honeypot??0)+(stats?.requests_routed_to_real??0);
  const percentage=total ? Math.round(100*(stats?.requests_routed_to_honeypot??0)/total) : 0;
  const recent=snapshot?.events.filter(event => event.suspicious || (event.risk_score??0)>0).slice(0,6) ?? [];
  const activeCount = organization.protections.filter(protection => protection.enabled && protection.status === 'active').length;
  const protectedDomain = domains.find(domain => domain.id === activeProtection?.domain_id);
  const protectedAgent = agents.find(agent => agent.domain_id === activeProtection?.domain_id && agent.status === 'healthy');
  const ready = Boolean(activeProtection && protectedDomain?.verified && protectedAgent && !organization.error);
  return <div className="overview-page">
    <header className="overview-heading"><div><p className="eyebrow">YOUR SECURITY OPERATIONS, IN FOCUS</p><h1>Security overview<span className="heading-dot">.</span></h1><p>See the intent. Contain the impact. Follow the evidence.</p></div><div className="overview-sync"><span className={`feed-status ${error ? 'disconnected' : ''}`}><i />{error ? 'Feed interrupted' : loading ? 'Connecting to telemetry' : 'Telemetry connected'}</span><small>{updated ? `Updated ${time(updated.toISOString())}` : 'Waiting for first snapshot'}</small><Button variant="secondary" size="small" disabled={refreshing} icon={<Icon name="refresh" />} onClick={() => {void refresh();void organization.refresh();}}>{refreshing ? 'Refreshing…' : 'Refresh snapshot'}</Button></div></header>
    {(error || organization.error) && <div className="ui-alert ui-alert-error" role="alert"><Icon name="alert" /><div><strong>Some security data is unavailable</strong><p>{error || organization.error} {snapshot ? 'The last successful snapshot is still visible.' : 'Refresh to try again.'}</p></div></div>}
    <div className={`posture-banner ${ready ? 'ready' : ''}`}><span className="posture-icon"><Icon name="shield" /></span><div><strong>{orgLoading ? 'Checking your environment' : organization.error ? 'Environment status needs a refresh' : ready ? 'Your security layer is active' : activeProtection ? 'Protection configured · review agent health' : 'Complete your security setup'}</strong><p>{activeProtection ? `${protectedDomain?.domain || 'Registered environment'} · ${activeCount} active ${activeCount === 1 ? 'protection' : 'protections'} · ${protectedAgent ? 'Healthy agent reported' : 'Awaiting a healthy agent for this domain'}` : 'Verify a domain, connect your agent, and confirm protection readiness.'}</p></div><Link to={activeProtection ? '/dashboard/protection' : '/onboarding'}>{activeProtection ? 'View protection' : 'Continue setup'} <Icon name="arrow" /></Link></div>
    <section className="overview-metrics" aria-label="Security metrics">
      <Link to={organization.domains.length ? '/dashboard/settings' : '/onboarding/domain'}><div><Icon name="globe" /><span>Verified domains</span></div><strong>{orgLoading ? '—' : domains.filter(d=>d.verified).length}<small>/ {orgLoading ? '—' : domains.length}</small></strong><p>Ownership-confirmed environments <span>↗</span></p></Link>
      <Link to="/dashboard/agent"><div><Icon name="server" /><span>Healthy agents</span></div><strong>{orgLoading ? '—' : agents.filter(a=>a.status==='healthy').length}<small>/ {orgLoading ? '—' : agents.length}</small></strong><p>Based on last reported health <span>↗</span></p></Link>
      <Link to="/dashboard/incidents" className="metric-attention"><div><Icon name="alert" /><span>Correlated incidents</span></div><strong>{stats?.total_incidents ?? '—'}</strong><p>Sessions with investigation evidence <span>↗</span></p></Link>
      <Link to="/dashboard/events"><div><Icon name="layers" /><span>Requests diverted</span></div><strong>{stats?.requests_routed_to_honeypot ?? '—'}</strong><p>{percentage}% of recorded routing decisions <span>↗</span></p></Link>
    </section>
    <div className="overview-investigations"><section className="surface investigation-queue"><div className="surface-heading"><div><p className="eyebrow">INVESTIGATION QUEUE</p><h2>What needs your attention</h2></div><Link to="/dashboard/incidents" className="text-link">All incidents ↗</Link></div>
      {loading ? <div className="skeleton-list" role="status" aria-label="Loading incidents"><i/><i/><i/></div> : !snapshot?.incidents.length ? <EmptyState icon={<Icon name="shield" />} title="No correlated incidents yet" description="Observed deception activity will appear here. Configure protection or run the local PhantomBank scenario." action={<Link className="text-link" to="/dashboard/protection">Review your protection →</Link>} /> : <div className="overview-queue">{snapshot.incidents.slice(0,3).map(incident=><Link key={incident.incident_id} className="queue-row" to={`/dashboard/incidents/${incident.incident_id}`}><div className={`risk-tile ${incident.risk_score>=76?'critical':''}`}><strong>{incident.risk_score}</strong><small>RISK</small></div><div className="queue-copy"><strong>{human(incident.attack_stage || 'Suspicious activity')}</strong><p>{incident.session_id.startsWith('bank:')?'PhantomBank':'Protected session'} <span>·</span> {incident.interaction_count} interactions</p><code title={incident.session_id}>{incident.session_id.slice(-12)}</code></div><div className="queue-meta"><StatusPill status={incident.severity} size="small" dot={false}/><time dateTime={incident.created_at}>{time(incident.created_at)}</time><span className="queue-link">Investigate ↗</span></div></Link>)}</div>}
    </section><aside className="surface overview-brief"><div className="surface-heading"><div><p className="eyebrow">LATEST SESSION</p><h2>{lead ? 'Intent becomes evidence.' : 'Ready for the first signal.'}</h2></div><Icon name="activity" /></div><div className="brief-risk"><div className="risk-dial" style={{background:`conic-gradient(var(--violet) ${(lead?.risk_score??0)*3.6}deg, var(--line) 0deg)`}}><div><strong>{lead?.risk_score ?? '—'}</strong><span>/ 100 RISK</span></div></div><div><StatusPill status={lead?.severity || 'pending'} size="small"/><h3>{lead ? human(lead.attack_stage || 'investigation') : 'Awaiting telemetry'}</h3><p>{lead ? `${lead.interaction_count} observed interactions` : 'No manufactured activity.'}</p></div></div><p className="brief-description">{lead ? 'Inspect the operations, rule matches, and synthetic exposure behind this score.' : 'Suspicious requests create a session, a timeline, and a tenant-owned incident.'}</p><Link className="ui-primary overview-primary" to={lead ? `/dashboard/incidents/${lead.incident_id}` : '/onboarding'}>{lead ? 'Open latest investigation' : 'Configure protection'}<Icon name="arrow" /></Link><div className="brief-advisory"><Icon name="lock" /><p><strong>Evidence first. Analysis second.</strong><br/>The current analysis provider is a labeled deterministic mock. Intent is an inference, never an enforcement control.</p></div></aside></div>
    <section className="surface overview-path"><div className="surface-heading"><div><p className="eyebrow">THE PROTECTION PATH</p><h2>Same application. A different destination.</h2></div><span className="subtle-tag">Deterministic routing</span></div><div className="live-routing"><div><Icon name="globe"/><strong>Request</strong><small>Customer application</small></div><Icon name="arrow"/><div className="route-engine"><Icon name="shield"/><strong>Detect + assess</strong><small>Rules & session history</small></div><Icon name="arrow"/><div className="route-choice"><span><i className="status-dot green"/><strong>Real environment</strong><b>{stats?.requests_routed_to_real ?? '—'}</b></span><span><i className="status-dot violet"/><strong>Isolated deception</strong><b>{stats?.requests_routed_to_honeypot ?? '—'}</b></span></div><Icon name="arrow"/><div><Icon name="activity"/><strong>Evidence</strong><small>{stats?.honeypot_interactions ?? '—'} deception interactions</small></div></div><p className="surface-footnote">Metadata and synthetic counts only. Routing counts show decisions, not independent proof of every database access.</p></section>
    <section className="surface overview-evidence"><div className="surface-heading"><div><p className="eyebrow">RECENT SUSPICIOUS ACTIVITY</p><h2>The signals behind the story</h2></div><Link to="/dashboard/events" className="text-link">Open event console ↗</Link></div>{recent.length ? <div className="evidence-feed">{recent.map(event=><Link key={event.event_id} to={`/dashboard/events${event.session_id ? `?session=${encodeURIComponent(event.session_id)}` : ''}`} className="evidence-row"><span className="evidence-time"><i/>{time(event.timestamp)}</span><span className="evidence-operation"><code>{event.operation}</code><small>{human(event.event_type || 'recorded event')}</small></span><span title={event.session_id || ''} className="evidence-session">{event.session_id?.slice(-12) || 'Assessment'}</span><span className={event.final_target === 'honeypot' ? 'destination-deception' : 'destination-other'}>{event.final_target === 'honeypot' ? 'DECEPTION' : event.final_target?.toUpperCase() || 'ASSESSMENT'}</span><strong>{event.risk_score ?? '—'}<small> risk</small></strong></Link>)}</div> : <EmptyState title={loading ? 'Loading the latest signals…' : 'No suspicious activity in the latest feed'} description="Ordinary decisions remain available in the complete event console." />}</section>
  </div>;
}
